// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:1cb240fe-d77a-4f4b-b9df-dd12798b4b17",
    "aws_cognito_region": "us-west-2",
    "oauth": {},
    "aws_mobile_analytics_app_id": "a0b2f0991a554f589bcbdd029412669f",
    "aws_mobile_analytics_app_region": "us-west-2"
};


export default awsmobile;
