// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:e4b3666c-820a-4874-add0-88306dac395c',
    'aws_cognito_region': 'us-east-1',
    'aws_mobile_analytics_app_id': '8029d2517f3349cabc741bda3fefbee1',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '5eb362ee-83ee-4c0a-ab3d-36a48701bcf5',
    'aws_project_name': 'Living Window',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'livingwindow-mobilehub-1988115350',
}

export default awsmobile;
