// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
var aws_app_analytics = 'enable';
var aws_cognito_identity_pool_id = 'us-west-2:b2629d16-b51a-43a9-920d-031d0619ae97';
var aws_cognito_region = 'us-west-2';
var aws_mobile_analytics_app_id = 'fdc7c764ae994c25bb9dc5a07bb1138e';
var aws_mobile_analytics_app_region = 'us-east-1';
var aws_project_id = '69ef6e92-77ce-4769-b8ff-e75c5fde7848';
var aws_project_name = 'Plant Wrangler';
var aws_project_region = 'us-west-2';
var aws_resource_name_prefix = 'plantwrangler-mobilehub-468688623';
var aws_sign_in_enabled = 'enable';
var aws_user_files = 'enable';
var aws_user_files_s3_bucket = 'plantwrangler-userfiles-mobilehub-468688623';
var aws_user_files_s3_bucket_region = 'us-west-2';
var aws_user_pools = 'enable';
var aws_user_pools_id = 'us-west-2_NKllJfqZf';
var aws_user_pools_mfa_type = 'OFF';
var aws_user_pools_web_client_id = '1gs78bajgcpo34d4ne1ihvcc8a';

AWS.config.region = aws_project_region;
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: aws_cognito_identity_pool_id
  }, {
    region: aws_cognito_region
  });
AWS.config.update({customUserAgent: 'MobileHub v0.1'});
